#version: 2
#updates:
#  # NOTE: not compatible with paket, see https://github.com/dependabot/dependabot-core/issues/2190
#  - package-ecosystem: "nuget"
#    directory: "/"
#    schedule:
#      interval: "daily"
#  - package-ecosystem: "docker"
#    directory: "/"
#    schedule:
#      interval: "daily"
#  - package-ecosystem: "github-actions"
#    directory: "/"
#    schedule:
#      interval: "daily"
